#!/usr/bin/env bash

set -euo pipefail

is_up() {
	local service="$1"
	local result
	result="$(s6-svstat "/run/service/${service}" -o up)"
	test "${result}" = "true"
}

is_up open-balena-s3
mc ls localhost
