#!/usr/bin/env bash

set -euo pipefail

# https://skarnet.org/software/s6/s6-svstat.html
is_up() {
	local service="$1"
	local result
	result="$(s6-svstat -u "/run/service/${service}")"
	test "${result}" = "true"
}

is_up open-balena-s3
mc ls localhost
