#!/usr/src/env bash
# shellcheck disable=SC1090,SC2154

workdir=/usr/src/app/
envfile=config/env

cd "${workdir}" || exit 1

set -a
[[ -f "${envfile}" ]] && source "${envfile}"
set +a

exec /go/bin/minio server --address ":80" --console-address ":43697" /export
